import type { Metadata } from "next";
// import { Roboto } from "next/font/google";
import { Geist } from "next/font/google";
import "./globals.css";
import Provider from "./provider";
import { Toaster } from "sonner";

const geist = Geist({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
});

// const roboto = Roboto({
//   subsets: ["latin"],
//   weight: ["400"],
//   display: "swap",
// });

export const metadata: Metadata = {
  title: "Lasu Recommendation App",
  description: "Generated by Prof Daniel",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={geist.className}>
      <body>
        <Provider>{children}</Provider>
        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
