import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import QueryProvider from "./queryProvider";
import { Toaster } from "sonner";
import { StudentProvider } from "@/contexts/studentContext";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Lasu Recommendation App",
  description: "Generated by Prof Daniel",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.className} data-scroll-behavior="smooth">
      <body>
        <QueryProvider>
          <StudentProvider>{children}</StudentProvider>
        </QueryProvider>
        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
